// GENERATED by scripts/fetch-fonts.mjs — do not hand-edit; re-run the fetcher.
// Hand-editing this file or fonts.css alone is how a preload and an @font-face drift apart.

/** The woff2 files needed for the FIRST PAINT — the display face in the H1's weight. */
export const FONT_PRELOAD: string[] = [
  "/fonts/fredoka-400-700.woff2"
];

/** What tokens.css --font-display / --font-body must resolve to at runtime.
 *  check-fonts.mjs asserts the rendered H1 and body actually use these. */
export const FONT_FAMILIES: { display: string; body: string } = {
  "display": "Fredoka",
  "body": "Nunito"
};
