// kit:generate@1.0.0 — shared engine for repeated-shape page generators.
import fs from 'node:fs';
import path from 'node:path';

export const GENERATED_HEADER = (script) =>
  `// GENERATED by scripts/${script} — edit the data file, not this page.`;

/** Round-robin destination + label rotation so a template cannot concentrate its link graph. */
export function rotateLink(index, hubs, selfPath) {
  const pool = hubs.filter((h) => h.path !== selfPath);
  if (!pool.length) return null;
  const dest = pool[index % pool.length];
  const LABELS = [
    (t) => t,
    (t) => `the ${t.toLowerCase()} guide`,
    (t) => `how ${t.toLowerCase()} works`,
    (t) => `compare ${t.toLowerCase()}`,
    (t) => `${t.toLowerCase()} costs`,
  ];
  return { href: dest.path, label: LABELS[index % LABELS.length](dest.title) };
}

/**
 * Emit pages from records.
 *  opts.script   name of the calling script (for the header comment)
 *  opts.records  [{ slug, outPath, ...fields }]
 *  opts.render   (record, ctx) => file body (WITHOUT the header comment)
 *  opts.write    boolean
 */
export function emit(opts) {
  const { script, records, render, write } = opts;
  const rows = []; let drift = 0;
  for (const [i, r] of records.entries()) {
    const body = `${GENERATED_HEADER(script)}\n${render(r, { index: i })}`;
    const out = r.outPath;
    const existing = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : null;
    if (existing !== null && existing.trim() === body.trim()) { rows.push([r.slug, 'SAME']); continue; }
    drift++;
    if (write) {
      fs.mkdirSync(path.dirname(out), { recursive: true });
      fs.writeFileSync(out, body, 'utf8');
      rows.push([r.slug, existing === null ? 'CREATED' : 'UPDATED']);
    } else {
      rows.push([r.slug, existing === null ? 'MISSING' : 'STALE']);
    }
  }
  console.log('SLUG                          | STATUS');
  for (const [s, st] of rows) console.log(`${String(s).padEnd(29)} | ${st}`);
  console.log(`\n${script}: records=${records.length} drift=${drift} mode=${write ? 'WRITE' : 'CHECK'}`);
  if (write && drift) console.log('NOTE shared blocks changed — run `astro build` and full QC now.');
  console.log(drift && !write ? `FAIL ${script} (emitted pages are stale — run with --write)` : `PASS ${script}`);
  return drift && !write ? 1 : 0;
}

export function loadData(file) {
  if (!fs.existsSync(file)) throw new Error(`[generate] missing data file ${file}`);
  return file;
}
