#!/usr/bin/env python3
"""build_sme_quotes.py — config/sme/quotes/*.json  →  src/data/sme-quotes.ts  (verbatim, by id).

Usage:
    python scripts/build_sme_quotes.py [--project .]            # validate + (re)generate src/data/sme-quotes.ts
    python scripts/build_sme_quotes.py [--project .] --check    # validate + compare; exit 1 if invalid or stale
Prints a PASS/FAIL table (one row per check + per category); exit 1 on any FAIL.
"""
import argparse
import glob
import json
import os
import re
import sys
from pathlib import Path

VALUE_TESTS = {"number", "mechanism", "runnable-test", "corrected-misconception"}
KINDS = {"expert", "editorial"}
CONSENTS = {"cited — attribution only", "cited - attribution only", "yes", "anonymize"}
VERIFIED = {"caption-track", "transcript-file", "none"}
REQ_STR = ["id", "quote", "speaker", "credential", "publisher", "source_url", "timestamp", "kind", "consent",
           "verified_against", "value_test", "why", "caution", "category"]
TS_HEADER = "// GENERATED by scripts/build_sme_quotes.py from config/sme/quotes/*.json — DO NOT EDIT BY HAND.\n" \
            "// Quotes are VERBATIM; fix the JSON (or drop the quote) and re-run the script.\n"


def ts_str(s):
    return json.dumps(s, ensure_ascii=False)


def load(project):
    files = sorted(glob.glob(str(Path(project) / "config" / "sme" / "quotes" / "*.json")))
    entries, problems = [], []
    for f in files:
        cat = Path(f).stem
        try:
            data = json.loads(Path(f).read_text(encoding="utf-8"))
        except ValueError as e:
            problems.append((cat, "-", f"invalid JSON: {e}"))
            continue
        if not isinstance(data, list):
            problems.append((cat, "-", "top level must be an array"))
            continue
        for i, q in enumerate(data):
            if not isinstance(q, dict):
                problems.append((cat, f"#{i}", "entry is not an object")); continue
            qid = str(q.get("id", f"#{i}"))
            for k in REQ_STR:
                if k not in q or not isinstance(q[k], str) or (not q[k].strip() and k not in ("caution", "credential", "publisher")):
                    problems.append((cat, qid, f"missing/empty string field '{k}'"))
            if q.get("verify") is not False:
                problems.append((cat, qid, "verify must be false (verify:true never ships)"))
            if q.get("value_test") not in VALUE_TESTS:
                problems.append((cat, qid, f"value_test must be one of {sorted(VALUE_TESTS)}"))
            if q.get("kind") not in KINDS:
                problems.append((cat, qid, "kind must be expert|editorial"))
            if q.get("consent") not in CONSENTS:
                problems.append((cat, qid, "consent must be 'cited — attribution only' | yes | anonymize"))
            if q.get("verified_against") not in VERIFIED:
                problems.append((cat, qid, "verified_against must be caption-track|transcript-file|none"))
            quote = q.get("quote", "")
            if "—" in quote or "–" in quote:
                problems.append((cat, qid, "em/en dash inside quote — DROP the quote, never edit it"))
            if re.search(r"\d", quote) and q.get("verified_against") == "none":
                problems.append((cat, qid, "quote carries a number but verified_against = none"))
            if not re.match(r"^https?://", q.get("source_url", "")):
                problems.append((cat, qid, "source_url must be an http(s) URL"))
            if not re.fullmatch(r"\d{1,2}:\d{2}:\d{2}|\d{1,2}:\d{2}|n/a", q.get("timestamp", "")):
                problems.append((cat, qid, "timestamp must be hh:mm:ss (or n/a for text sources)"))
            if q.get("category") and q["category"] != cat:
                problems.append((cat, qid, f"category '{q.get('category')}' != file name '{cat}'"))
            if not isinstance(q.get("pages", []), list):
                problems.append((cat, qid, "pages must be an array"))
            if q.get("used_on") is not None and not isinstance(q.get("used_on"), str):
                problems.append((cat, qid, "used_on must be null or a slug string"))
            q.setdefault("category", cat)
            q.setdefault("pages", [])
            q.setdefault("used_on", None)
            entries.append(q)
    # cross-file rules
    ids = {}
    for q in entries:
        ids.setdefault(q.get("id"), []).append(q.get("category"))
    for qid, cats in ids.items():
        if len(cats) > 1:
            problems.append(("*", qid, f"duplicate id across {cats}"))
    texts = {}
    for q in entries:
        key = re.sub(r"\s+", " ", q.get("quote", "")).strip().lower()
        texts.setdefault(key, []).append(q.get("id"))
    for key, qids in texts.items():
        if len(qids) > 1 and key:
            problems.append(("*", ",".join(map(str, qids)), "same quote text in two entries"))
    used = {}
    for q in entries:
        if q.get("used_on"):
            used.setdefault(q["used_on"], []).append(q.get("id"))
    for q in entries:
        if q.get("used_on") and sum(1 for e in entries if e.get("quote") == q.get("quote") and e.get("used_on") and e.get("used_on") != q.get("used_on")):
            problems.append(("*", q.get("id"), "same quote used_on two indexed pages"))
    return files, entries, problems


def render_ts(entries):
    out = [TS_HEADER,
           "export interface SmeQuote {",
           "  id: string; quote: string; speaker: string; credential: string; publisher: string;",
           "  source_url: string; timestamp: string; kind: 'expert' | 'editorial'; consent: string;",
           "  verified_against: 'caption-track' | 'transcript-file' | 'none';",
           "  value_test: 'number' | 'mechanism' | 'runnable-test' | 'corrected-misconception';",
           "  why: string; caution: string; category: string; pages: string[]; used_on: string | null;",
           "}", "",
           "export const SME_QUOTES: SmeQuote[] = ["]
    for q in sorted(entries, key=lambda e: (e.get("category", ""), e.get("id", ""))):
        out.append("  {")
        for k in ("id", "quote", "speaker", "credential", "publisher", "source_url", "timestamp", "kind", "consent",
                  "verified_against", "value_test", "why", "caution", "category"):
            out.append(f"    {k}: {ts_str(q.get(k, ''))},")
        out.append(f"    pages: {json.dumps(q.get('pages', []), ensure_ascii=False)},")
        out.append(f"    used_on: {ts_str(q['used_on']) if q.get('used_on') else 'null'},")
        out.append("  },")
    out += ["];", "",
            "export const SME_QUOTES_BY_ID: Record<string, SmeQuote> = Object.fromEntries(SME_QUOTES.map(q => [q.id, q]));",
            "export const SME_CATEGORIES: string[] = Array.from(new Set(SME_QUOTES.map(q => q.category)));",
            "export function quotesFor(slug: string): SmeQuote[] {",
            "  return SME_QUOTES.filter(q => q.used_on === slug || q.pages.includes(slug));",
            "}",
            "export function poolFor(category: string): SmeQuote[] {",
            "  return SME_QUOTES.filter(q => q.category === category && !q.used_on);",
            "}", ""]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", default=".")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:  # noqa: BLE001
        pass
    project = Path(a.project).resolve()
    files, entries, problems = load(project)
    rows = []
    rows.append(("PASS" if files else "FAIL", "quote files", f"{len(files)} file(s) in config/sme/quotes/"))
    by_cat = {}
    for q in entries:
        by_cat[q.get("category")] = by_cat.get(q.get("category"), 0) + 1
    for cat, n in sorted(by_cat.items()):
        rows.append(("PASS" if n >= 3 else "FAIL", f"category {cat}", f"{n} quote(s) (floor 3)"))
    for cat, qid, msg in problems:
        rows.append(("FAIL", f"{cat}/{qid}", msg))
    ts_path = project / "src" / "data" / "sme-quotes.ts"
    rendered = render_ts(entries)
    if a.check:
        cur = ts_path.read_text(encoding="utf-8").replace("\r\n", "\n") if ts_path.is_file() else ""
        rows.append(("PASS" if cur == rendered else "FAIL", "src/data/sme-quotes.ts", "matches JSON (verbatim, by id)" if cur == rendered else "STALE or missing — run without --check"))
    else:
        if not problems:
            ts_path.parent.mkdir(parents=True, exist_ok=True)
            ts_path.write_text(rendered, encoding="utf-8")
            rows.append(("PASS", "src/data/sme-quotes.ts", f"written ({len(entries)} quotes)"))
        else:
            rows.append(("FAIL", "src/data/sme-quotes.ts", "NOT written — fix the FAIL rows above"))
    w = max([len(r[1]) for r in rows] + [10])
    fails = 0
    print(f"build_sme_quotes {'--check' if a.check else ''} ({project})")
    for st, name, msg in rows:
        fails += st == "FAIL"
        print(f"{st:<5} {name:<{w}} {msg}")
    print(f"{'FAIL' if fails else 'PASS'}: {fails} failing check(s); quotes={len(entries)} categories={len(by_cat)} (rollup computed from rows)")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
