#!/usr/bin/env python
"""build_review_wall.py - generate src/data/review-wall.ts from the real Google pull.

  python scripts/build_review_wall.py            # regenerate
  python scripts/build_review_wall.py --check    # exit 1 if the .ts is stale

WHY THIS IS SEPARATE FROM build_reviews.py
------------------------------------------
scripts/build_reviews.py owns src/data/reviews.ts, which is a PULL-QUOTE bank: it
applies a 12-word floor because a four-word review makes a poor testimonial sitting
next to body copy, and it is sampled deterministically across the silo so no single
review dominates.

The /reviews/ page has the opposite job. It is the complete public record, so a short
review belongs on it, and it needs the media (customer photos, reviewer avatars) that
the pull-quote bank has no use for. Two different jobs, two generated files, one
source of truth in sme/raw/google-reviews.json. Neither script edits the other's file.

Photos and avatars are downloaded and converted by scripts/fetch_review_media.py into
src/assets/reviews/, and referenced here by FILENAME only, so the page can resolve them
through import.meta.glob and let Astro optimise and size them. Nothing hotlinks
lh3.googleusercontent.com: those URLs are unstable and would put a third-party request
on the critical path of a money page.

Reviews are copied VERBATIM with the reviewer's own name. Nothing here edits a review.
"""
import argparse
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SRC = Path("sme/raw/google-reviews.json")
MEDIA = Path("src/data/review-media.json")
OUT = Path("src/data/review-wall.ts")

HEADER = (
    "// GENERATED by scripts/build_review_wall.py from the real Google Business Profile\n"
    "// pull. DO NOT EDIT BY HAND. Reviews are verbatim, with the reviewer's own name.\n"
    "// Photos are local files in src/assets/reviews/ (scripts/fetch_review_media.py).\n"
)

IFACE = (
    "export interface WallReview {\n"
    "  id: string;\n"
    "  quote: string;\n"
    "  name: string;\n"
    "  rating: number | null;\n"
    "  timeAgo: string;\n"
    "  url: string;\n"
    "  /** filenames under src/assets/reviews/, resolved by the page via import.meta.glob */\n"
    "  photos: string[];\n"
    "  avatar: string | null;\n"
    "  localGuide: boolean;\n"
    "  reviewsCount: number;\n"
    "}\n"
)


def load():
    if not SRC.exists():
        sys.exit("missing %s - pull the Google reviews first" % SRC)
    media = json.loads(MEDIA.read_text(encoding="utf-8")) if MEDIA.exists() else {}
    rows = json.loads(SRC.read_text(encoding="utf-8"))
    out = []
    for i, r in enumerate(rows):
        name = (r.get("profile_name") or "").strip()
        if not name:
            continue
        rid = r.get("review_id") or ("r%d" % r.get("rank_absolute", i))
        m = media.get(rid) or {}
        rating = r.get("rating")
        out.append({
            "id": rid,
            "quote": (r.get("review_text") or "").strip(),
            "name": name,
            "rating": rating.get("value") if isinstance(rating, dict) else rating,
            "timeAgo": r.get("time_ago") or "",
            "url": r.get("review_url") or "",
            "photos": [p for p in (m.get("photos") or [])],
            "avatar": m.get("avatar"),
            "localGuide": bool(r.get("local_guide")),
            "reviewsCount": r.get("reviews_count") or 0,
            "_pos": i,
        })
    # Reviews carrying a real customer photo lead the wall, because a photo is the part
    # a reader cannot argue with. Source order is newest-first, so _pos keeps recency
    # inside each group. A review with no text at all sinks to the bottom: a bare star
    # rating is true but says nothing, and it should not take a top slot.
    out.sort(key=lambda e: (0 if e["photos"] else 1, 0 if e["quote"] else 1, e["_pos"]))
    for e in out:
        e.pop("_pos")
    return out


def ts(entries):
    j = lambda v: json.dumps(v, ensure_ascii=False)
    body = [HEADER, IFACE, "export const REVIEW_WALL: WallReview[] = ["]
    for e in entries:
        body.append("  {")
        body.append("    id: %s," % j(e["id"]))
        body.append("    quote: %s," % j(e["quote"]))
        body.append("    name: %s," % j(e["name"]))
        body.append("    rating: %s," % (e["rating"] if e["rating"] is not None else "null"))
        body.append("    timeAgo: %s," % j(e["timeAgo"]))
        body.append("    url: %s," % j(e["url"]))
        body.append("    photos: %s," % j(e["photos"]))
        body.append("    avatar: %s," % j(e["avatar"]))
        body.append("    localGuide: %s," % ("true" if e["localGuide"] else "false"))
        body.append("    reviewsCount: %d," % e["reviewsCount"])
        body.append("  },")
    body.append("];")
    body.append("")
    body.append("/** Reviews that carry at least one real customer photo. */")
    body.append("export const REVIEWS_WITH_PHOTOS = REVIEW_WALL.filter((r) => r.photos.length > 0);")
    body.append("")
    return "\n".join(body) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    entries = load()
    text = ts(entries)
    if a.check:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        ok = cur == text
        print("review-wall: %d reviews, %d with photos; %s %s"
              % (len(entries),
                 sum(1 for e in entries if e["photos"]),
                 OUT,
                 "up to date" if ok else "STALE"))
        return 0 if ok else 1
    OUT.write_text(text, encoding="utf-8")
    print("review-wall: wrote %d reviews (%d with photos) to %s"
          % (len(entries), sum(1 for e in entries if e["photos"]), OUT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
