#!/usr/bin/env python
"""build_reviews.py - generate src/data/reviews.ts from the real Google review pull.

  python scripts/build_reviews.py            # regenerate
  python scripts/build_reviews.py --check    # exit 1 if the .ts is stale or invalid

Source of truth is sme/raw/google-reviews.json, pulled from the Google Business Profile via the
DataForSEO Business Data API. Reviews are copied VERBATIM with the reviewer's own name. Nothing
here edits a review: no grammar cleanup, no breed swapping, no re-attribution. If a review reads
awkwardly, that is what the customer wrote and it stays.

Why this file exists: review cards used to be pasted into each page by hand, which produced two
mis-attributions and two silently edited quotes across 61 page placements, and put the same two
reviews on 45 pages each. A generated registry makes all four of those impossible.
"""
import argparse
import json
import os
import re
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SRC = Path("sme/raw/google-reviews.json")
OUT = Path("src/data/reviews.ts")
HEADER = (
    "// GENERATED by scripts/build_reviews.py from the real Google Business Profile pull.\n"
    "// DO NOT EDIT BY HAND. Reviews are verbatim, with the reviewer's own name.\n"
    "// Re-pull the source, then re-run the script.\n"
)
MIN_WORDS = 12


def load():
    if not SRC.exists():
        sys.exit("missing %s - pull the Google reviews first" % SRC)
    rows = json.loads(SRC.read_text(encoding="utf-8"))
    out = []
    for r in rows:
        text = (r.get("review_text") or "").strip()
        name = (r.get("profile_name") or "").strip()
        if not text or not name:
            continue
        if len(text.split()) < MIN_WORDS:
            continue
        # An em dash inside a real review is left alone: the house style governs our prose,
        # not a customer's words. It is flagged so a human can choose a different quote.
        out.append({
            "id": r.get("review_id") or ("r%d" % r.get("rank_absolute", 0)),
            "quote": text,
            "name": name,
            "rating": r.get("rating", {}).get("value") if isinstance(r.get("rating"), dict) else r.get("rating"),
            "timeAgo": r.get("time_ago") or "",
            "url": r.get("review_url") or "",
            "hasEmDash": "—" in text,
        })
    return out


def ts(entries):
    body = [HEADER,
            "export interface GoogleReview {\n"
            "  id: string; quote: string; name: string; rating: number | null;\n"
            "  timeAgo: string; url: string;\n}\n",
            "export const GOOGLE_REVIEWS: GoogleReview[] = ["]
    for e in entries:
        body.append("  {")
        body.append("    id: %s," % json.dumps(e["id"], ensure_ascii=False))
        body.append("    quote: %s," % json.dumps(e["quote"], ensure_ascii=False))
        body.append("    name: %s," % json.dumps(e["name"], ensure_ascii=False))
        body.append("    rating: %s," % (e["rating"] if e["rating"] is not None else "null"))
        body.append("    timeAgo: %s," % json.dumps(e["timeAgo"], ensure_ascii=False))
        body.append("    url: %s," % json.dumps(e["url"], ensure_ascii=False))
        body.append("  },")
    body.append("];\n")
    body.append(
        "/** Deterministic, evenly spread selection so no review dominates the silo.\n"
        " *  Same slug always yields the same reviews, so the build is reproducible. */\n"
        "export function reviewsFor(slug: string, n = 3): GoogleReview[] {\n"
        "  const total = GOOGLE_REVIEWS.length;\n"
        "  if (total === 0) return [];\n"
        "  let h = 0;\n"
        "  for (let i = 0; i < slug.length; i++) h = (h * 31 + slug.charCodeAt(i)) >>> 0;\n"
        "  const start = h % total;\n"
        "  const stride = Math.max(1, Math.floor(total / Math.max(1, n)));\n"
        "  const out: GoogleReview[] = [];\n"
        "  const seen = new Set<string>();\n"
        "  for (let i = 0; out.length < Math.min(n, total); i++) {\n"
        "    const r = GOOGLE_REVIEWS[(start + i * stride + (i % stride)) % total];\n"
        "    if (seen.has(r.id)) continue;\n"
        "    seen.add(r.id);\n"
        "    out.push(r);\n"
        "  }\n"
        "  return out;\n"
        "}\n\n"
        "/** Carousel-shaped selection: {quote, name, meta}, still verbatim. */\n"
        "export function testimonialsFor(slug: string, n = 3) {\n"
        "  return reviewsFor(slug, n).map((r) => ({\n"
        "    quote: r.quote,\n"
        "    name: r.name,\n"
        "    meta: r.timeAgo ? `Google review, ${r.timeAgo}` : 'Google review',\n"
        "  }));\n"
        "}\n")
    return "\n".join(body) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    entries = load()
    text = ts(entries)
    dashes = [e["name"] for e in entries if e["hasEmDash"]]
    if a.check:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        ok = cur == text
        print("reviews: %d usable of source; src/data/reviews.ts %s"
              % (len(entries), "up to date" if ok else "STALE"))
        return 0 if ok else 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print("wrote %s with %d verbatim reviews" % (OUT, len(entries)))
    if dashes:
        print("note: %d review(s) contain an em dash and are left verbatim: %s"
              % (len(dashes), ", ".join(dashes)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
