#!/usr/bin/env node
// kit:fetch-fonts@1.0.0 — install the site's typefaces as SELF-HOSTED woff2.
//
// Usage:
//   node scripts/fetch-fonts.mjs "Inter Tight:600,700" "Inter:400,500"
//   node scripts/fetch-fonts.mjs --system            # deliberate system-ui, no web font
//   node scripts/fetch-fonts.mjs --check             # is the generated state consistent?
//
// The FIRST family is the display face (--font-display); the second, if given, is the body
// face (--font-body). The lowest weight of the display face is preloaded, because that is
// what the H1 paints with.
//
// Downloads once, at build-setup time, from the Google Fonts CSS2 API with a woff2-capable
// UA, writes the files into public/fonts/, then REGENERATES src/styles/fonts.css and
// src/styles/fonts.ts together. Nothing at runtime touches a third-party origin: the
// stylesheet is ours, the files are ours, and check-fonts.mjs measures that on the built
// page. A font the reader never receives is a design direction that never shipped.
import fs from 'node:fs';
import path from 'node:path';

const argv = process.argv.slice(2);
// `swap` shows the fallback then repaints in the web font, and that repaint IS a layout
// shift whenever the two faces have different metrics - the CLS that check-fonts reports
// and blames on "a font swap with no size-adjust". `optional` shows the fallback and
// never repaints, so the shift cannot happen; with a preloaded, self-hosted face the
// reader almost always gets the real font anyway. Choose per project, and record which.
const DISPLAY = (() => {
  const i = argv.indexOf('--display');
  const v = i === -1 ? 'swap' : argv[i + 1];
  if (!['swap', 'optional', 'fallback'].includes(v)) {
    console.error(`FAIL --display takes swap|optional|fallback, got "${v}"`);
    process.exit(2);
  }
  return v;
})();
const CSS = 'src/styles/fonts.css';
const TS = 'src/styles/fonts.ts';
const OUTDIR = path.join('public', 'fonts');
const TOKENS = 'src/styles/tokens.css';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';
const HEAD = fs.existsSync(CSS)
  ? fs.readFileSync(CSS, 'utf8').split('*/')[0] + '*/\n'
  : '/* kit:fonts@1.0.0 */\n';

const fail = (m) => { console.error(`FAIL ${m}`); process.exit(1); };

function writeTs(preload, families) {
  const body = `// GENERATED by scripts/fetch-fonts.mjs — do not hand-edit; re-run the fetcher.
// Hand-editing this file or fonts.css alone is how a preload and an @font-face drift apart.

/** The woff2 files needed for the FIRST PAINT — the display face in the H1's weight. */
export const FONT_PRELOAD: string[] = ${JSON.stringify(preload, null, 2).replace(/\n/g, '\n')};

/** What tokens.css --font-display / --font-body must resolve to at runtime.
 *  check-fonts.mjs asserts the rendered H1 and body actually use these. */
export const FONT_FAMILIES: { display: string; body: string } = ${JSON.stringify(families, null, 2)};
`;
  fs.writeFileSync(TS, body, 'utf8');
}

// ---------------------------------------------------------------- --check
if (argv.includes('--check')) {
  const css = fs.existsSync(CSS) ? fs.readFileSync(CSS, 'utf8') : '';
  const ts = fs.existsSync(TS) ? fs.readFileSync(TS, 'utf8') : '';
  const faces = [...css.matchAll(/@font-face\s*{[^}]*}/g)].map((m) => m[0]);
  const srcs = [...css.matchAll(/url\(['"]?([^'")]+)['"]?\)/g)].map((m) => m[1]);
  const preload = [...ts.matchAll(/["']([^"']+\.woff2)["']/g)].map((m) => m[1]);
  const problems = [];
  for (const f of faces) {
    if (!/font-display:\s*(swap|optional)/.test(f)) problems.push('an @font-face without font-display: swap');
    if (!/\.woff2/.test(f)) problems.push('an @font-face with no woff2 source');
  }
  for (const u of srcs) {
    if (/^https?:/.test(u)) { problems.push(`third-party font URL ${u}`); continue; }
    const f = path.join('public', u.replace(/^\//, ''));
    if (!fs.existsSync(f)) problems.push(`${u} is declared but not in public/fonts/`);
  }
  for (const u of preload) if (!srcs.includes(u)) problems.push(`FONT_PRELOAD names ${u}, which no @font-face uses`);
  if (faces.length && !preload.length) problems.push('web fonts are installed but nothing is preloaded');
  if (!faces.length && preload.length) problems.push('FONT_PRELOAD is non-empty with no @font-face declared');
  for (const p of problems) console.log('  ' + p);
  console.log(`\nfaces=${faces.length} files=${srcs.length} preload=${preload.length} problems=${problems.length}`);
  console.log(problems.length ? 'FAIL fetch-fonts --check' : 'PASS fetch-fonts --check');
  process.exit(problems.length ? 1 : 0);
}

// ---------------------------------------------------------------- --system
if (argv.includes('--system')) {
  fs.writeFileSync(CSS, HEAD + `
/* DELIBERATE SYSTEM STACK. No web font is installed; --font-display and --font-body in
   tokens.css must therefore name system-ui first, or the browser will hunt for a family
   that does not exist and check-fonts.mjs will fail the page. */
`, 'utf8');
  writeTs([], { display: 'system-ui', body: 'system-ui' });
  console.log('PASS fetch-fonts --system (no web font; set tokens.css to a system stack)');
  process.exit(0);
}

// ---------------------------------------------------------------- fetch
// A flag's VALUE is not a family name: `--display optional` used to be read as a family
// and sent to the font API, which answered 400 for "optional".
const FLAGS_WITH_VALUES = new Set(['--display']);
const specs = argv.filter((a, i) => !a.startsWith('--') && !FLAGS_WITH_VALUES.has(argv[i - 1]));
if (!specs.length) fail('name at least one family, e.g. "Inter Tight:600,700" (or pass --system).');

fs.mkdirSync(OUTDIR, { recursive: true });
const blocks = [];
const preload = [];
const families = { display: '', body: '' };

for (const [idx, spec] of specs.entries()) {
  const [familyRaw, weightsRaw] = spec.split(':');
  const family = familyRaw.trim();
  const weights = (weightsRaw || '400').split(',').map((w) => w.trim()).filter(Boolean).sort((a, b) => a - b);
  if (idx === 0) families.display = family;
  if (idx === 1) families.body = family;
  const api = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:wght@${weights.join(';')}&display=swap`;
  const res = await fetch(api, { headers: { 'User-Agent': UA } });
  if (!res.ok) fail(`Google Fonts returned ${res.status} for "${family}". Check the family name.`);
  const css = await res.text();
  const faces = [...css.matchAll(/@font-face\s*{([\s\S]*?)}/g)].map((m) => m[1]);
  if (!faces.length) fail(`no @font-face returned for "${family}".`);
  // The API emits one face per unicode-range subset. Keep the LATIN ones: a Cyrillic
  // subset nobody on this site can read is bytes on the critical path.
  // A VARIABLE font answers every requested weight with the SAME file. Downloading it
  // once per weight wrote four identical 35 KB copies on one site and blew the 120 KB
  // budget with 76 KB of real bytes. Group the latin faces by source URL, download each
  // file once, and emit ONE @font-face carrying the weight RANGE it covers.
  const byUrl = new Map();
  for (const face of faces) {
    const range = (face.match(/unicode-range:\s*([^;]+);/) || [, ''])[1];
    const isLatin = !range || /U\+0000-00FF|U\+0100-024F/i.test(range);
    if (!isLatin) continue;
    const weight = (face.match(/font-weight:\s*([^;]+);/) || [, '400'])[1].trim();
    const style = (face.match(/font-style:\s*([^;]+);/) || [, 'normal'])[1].trim();
    const url = (face.match(/url\((https:[^)]+\.woff2)\)/) || [, ''])[1];
    if (!url) continue;
    const key = `${url}|${style}`;
    if (!byUrl.has(key)) byUrl.set(key, { url, style, range, weights: [] });
    byUrl.get(key).weights.push(weight);
  }
  for (const { url, style, range, weights } of byUrl.values()) {
    const nums = weights.flatMap((w) => w.split(/\s+/).map(Number)).filter((n) => !Number.isNaN(n));
    const lo = Math.min(...nums), hi = Math.max(...nums);
    const weight = lo === hi ? String(lo) : `${lo} ${hi}`;
    const slug = `${family.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${lo === hi ? lo : `${lo}-${hi}`}${style === 'italic' ? '-italic' : ''}.woff2`;
    const bin = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!bin.ok) fail(`could not download ${url} (${bin.status}).`);
    fs.writeFileSync(path.join(OUTDIR, slug), Buffer.from(await bin.arrayBuffer()));
    const href = `/fonts/${slug}`;
    blocks.push(`@font-face {
  font-family: '${family}';
  font-style: ${style};
  font-weight: ${weight};
  font-display: ${DISPLAY};                 /* never block: a blank H1 is worse than a fallback one */
  src: url('${href}') format('woff2');
  ${range ? `unicode-range: ${range};` : ''}
}`);
    if (idx === 0 && !preload.length) preload.push(href);
    console.log(`  ${family} ${weight}${style === 'italic' ? ' italic' : ''} -> ${href} (${(fs.statSync(path.join(OUTDIR, slug)).size / 1024).toFixed(1)} KB)`);
  }
}

if (!families.body) families.body = families.display;
fs.writeFileSync(CSS, `${HEAD}\n${blocks.join('\n\n')}\n`, 'utf8');
writeTs(preload, families);

// The families must actually be NAMED by the token contract, or the browser downloads a
// font nothing asks for. This is a warning, not a failure: tokens.css is the site's file.
const tokens = fs.existsSync(TOKENS) ? fs.readFileSync(TOKENS, 'utf8') : '';
for (const f of new Set(Object.values(families))) {
  if (f && !tokens.includes(f)) console.log(`WARN "${f}" is not named in ${TOKENS} — set --font-display/--font-body.`);
}
console.log(`\nfaces=${blocks.length} preload=${preload.join(', ') || '(none)'}`);
console.log('PASS fetch-fonts — now run `npm run check:fonts` against a build.');
