#!/usr/bin/env node
// kit:gen-posts@1.0.0 — generate src/data/posts.ts from the blueprint + each page's own frontmatter.
// Usage: node scripts/gen-posts.mjs --check | --write
import fs from 'node:fs';
import path from 'node:path';
import { pageFiles, canonicalPath } from './lib/wire.mjs';

const write = process.argv.includes('--write');
const OUT = path.join('src', 'data', 'posts.ts');
import { parseCsv } from './lib/csv.mjs';
const SITE_DOMAIN = (() => { try { const m = fs.readFileSync('astro.config.mjs', 'utf8').match(/site:\s*['\"]([^'\"]+)['\"]/); return m ? m[1] : ''; } catch { return ''; } })();
const BLUEPRINT = path.join('research', 'site-blueprint.csv');

function blueprintRows() {
  if (!fs.existsSync(BLUEPRINT)) return new Map();
  const raw = parseCsv(fs.readFileSync(BLUEPRINT, 'utf8'));
  const rowsArr = raw.map((r) => r.cells ?? r);
  const head = rowsArr[0].map((h) => String(h).trim());
  const idx = (n) => head.indexOf(n);
  const map = new Map();
  for (const c of rowsArr.slice(1)) {
    const g = (n) => (idx(n) >= 0 ? String(c[idx(n)] ?? '').trim() : '');
    const p = g('url_slug') || g('path') || g('slug');
    if (!p) continue;
    map.set(canonicalPath(p), {
      title: g('title'),
      tier: g('tier') || g('page_tier'),
      hub: g('hub_or_node'),
      section: g('section_class'),
      parent: canonicalPath(g('parent') || '/'),
    });
  }
  return map;
}

// LAST RESORT for a description: the one the BUILT page actually ships. A page whose
// frontmatter description is a template literal has no readable value in the source, and
// the shipped <meta name="description"> is the honest text — never invent one.
function builtDescription(route) {
  const f = route === '/' ? 'dist/index.html' : `dist${route}index.html`;
  try {
    const m = fs.readFileSync(f, 'utf8').match(/<meta\s+name="description"\s+content="([^"]*)"/i);
    return m ? m[1].replace(/&amp;/g, '&').replace(/&#39;|&apos;/g, "'").replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>') : '';
  } catch { return ''; }
}

function frontmatter(file) {
  const src = fs.readFileSync(file, 'utf8');
  const out = {};
  for (const key of ['title', 'description', 'kicker', 'draft']) {
    const m = src.match(new RegExp(`^\\s*(?:const\\s+)?${key}\\s*[:=]\\s*(['"\`])([\\s\\S]*?)\\1`, 'm'));
    // A backtick frontmatter value is TEMPLATE SOURCE, not text: `${range}` read out of
    // the file is an unevaluated expression, and shipping it put "${site.license.avsNumber}"
    // in the RSS feed. Treat any value that still carries ${...} as unresolved so the
    // caller falls back to the blueprint's own copy.
    if (m) out[key] = /\$\{/.test(m[2]) ? '' : m[2];
    else if (key === 'draft' && /^\s*draft\s*[:=]\s*true/m.test(src)) out.draft = 'true';
  }
  out.noindex = /noindex/.test(src);
  return out;
}

const bp = blueprintRows();
const entries = pageFiles()
  .map(({ file, route }) => {
    const fm = frontmatter(file);
    const b = bp.get(route) || {};
    return {
      path: route,
      file: file.replace(/\\/g, '/'),
      // `??` only falls through on null/undefined, so a page whose title is a template
      // literal - which the frontmatter reader returns as '' - never reached the
      // blueprint fallback and was reported as having no title at all. (RTP Fix 2026-09-05)
      title: fm.title || b.title || '',
      description: fm.description || b.description || builtDescription(route) || '',
      kicker: fm.kicker ?? '',
      tier: b.tier ?? '',
      hub: b.hub ?? '',
      section: b.section ?? '',
      parent: b.parent ?? '/',
      draft: fm.draft === 'true',
      noindex: Boolean(fm.noindex),
    };
  })
  .sort((a, b) => a.path.localeCompare(b.path));

const missingTitle = entries.filter((e) => !e.title && !e.noindex);
const notInBlueprint = entries.filter((e) => !bp.has(e.path) && !e.noindex);

const body = `// Site: ${SITE_DOMAIN}
// GENERATED by scripts/gen-posts.mjs — edit the page frontmatter or the blueprint, never this file.
export interface PostEntry {
  path: string; file: string; title: string; description: string; kicker: string;
  tier: string; hub: string; section: string; parent: string; draft: boolean; noindex: boolean;
}
export const POSTS: PostEntry[] = ${JSON.stringify(entries, null, 2)};
export const ROUTES = POSTS;
export default POSTS;
`;

const existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
// kit-manifest.json declares src/data/posts.ts `kind: seed` - the PROJECT owns it, and
// site-kit.py refuses to overwrite it on update. This generator did overwrite it, and
// check:index failed until you let it, which on a hand-authored posts.ts destroyed the
// card teasers and cluster names the /blog index renders. Two instruments disagreeing
// about who owns a file is a defect in the pair, not in the site: if the file on disk
// does not carry this generator's banner, it is the project's and this is a no-op.
const GENERATED_BANNER = 'GENERATED by scripts/gen-posts.mjs';
const projectOwned = existing.trim() !== '' && !existing.includes(GENERATED_BANNER);
const drift = !projectOwned && existing.trim() !== body.trim();

console.log('CHECK                        | RESULT');
console.log(`pages found                  | ${entries.length}`);
console.log(`blueprint rows               | ${bp.size}`);
console.log(`pages missing a title        | ${missingTitle.length ? 'FAIL' : 'PASS'}`);
for (const e of missingTitle) console.log(`   ${e.path}`);
console.log(`pages not in the blueprint   | ${notInBlueprint.length ? 'FAIL' : 'PASS'}`);
for (const e of notInBlueprint) console.log(`   ${e.path}`);
console.log(`src/data/posts.ts up to date | ${projectOwned ? 'PASS (project-owned seed, not generated)' : drift ? 'FAIL (stale)' : 'PASS'}`);

if (write && projectOwned && !process.argv.includes('--force')) {
  console.log('');
  console.log('REFUSED ' + OUT + ' is a project-authored seed (no generator banner).');
  console.log('        Overwriting it would discard hand-written fields the site renders.');
  console.log('        Pass --force only if you mean to hand ownership to this generator.');
  process.exit(1);
}
if (write) {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body, 'utf8');
  console.log('\nPASS wrote ' + OUT + ' — now run `astro build` and full QC (shared blocks changed).');
  process.exit(missingTitle.length || notInBlueprint.length ? 1 : 0);
}
process.exit(drift || missingTitle.length || notInBlueprint.length ? 1 : 0);
