#!/usr/bin/env node
/**
 * gen-eeat.mjs — research/eeat-findings.json -> src/data/eeat.ts
 *
 *   node scripts/gen-eeat.mjs
 *   node scripts/gen-eeat.mjs --check
 *
 * The evidence bank (contracts.md §23) is researched at Stage 0.6 and assigned at Stage 1.
 * EeatFinding.astro reads it through the generated module so that the component — not the
 * writer — decides the hedge attribute, the limitation paragraph and the source list.
 *
 * --check exits 1 when src/data/eeat.ts is missing or older than the JSON, so a build cannot
 * silently render a stale bank. Node 20+, stdlib only.
 */
import fs from 'node:fs';
import path from 'node:path';

const argv = process.argv.slice(2);
const CHECK = argv.includes('--check');
const SRC = argv.find((a) => !a.startsWith('--')) || 'research/eeat-findings.json';
const OUT = path.join('src', 'data', 'eeat.ts');
const ex = (p) => { try { fs.accessSync(p); return true; } catch { return false; } };

if (!ex(SRC)) {
  console.error(`HALT: ${SRC} missing. Stage 0.6 (skill eeat-research) has not run for this project.`);
  console.error('      A build with no evidence bank is a build with no information-gain supply;');
  console.error('      it is not an empty file to generate past.');
  process.exit(1);
}

if (CHECK) {
  if (!ex(OUT)) { console.error(`FAIL: ${OUT} missing — run \`npm run gen:eeat\`.`); process.exit(1); }
  if (fs.statSync(OUT).mtimeMs < fs.statSync(SRC).mtimeMs) {
    console.error(`FAIL: ${OUT} is older than ${SRC} — the bank changed and the module was not regenerated.`);
    process.exit(1);
  }
  console.log(`gen-eeat --check: ${OUT} is present and newer than ${SRC}.`);
  process.exit(0);
}

const raw = JSON.parse(fs.readFileSync(SRC, 'utf8').replace(/^﻿/, ''));
const findings = raw.findings || [];
const TYPES = new Set(['Verified fact', 'Verified official guidance', 'Verified technical principle',
  'Documented professional practice', 'First-hand practitioner observation',
  'First-hand customer observation', 'Expert interpretation', 'Customer anecdote',
  'Hypothesis requiring validation']);

const problems = [];
for (const f of findings) {
  if (!/^E\d{2,3}$/.test(f.id || '')) problems.push(`bad id ${JSON.stringify(f.id)}`);
  if (!TYPES.has(f.type)) problems.push(`${f.id}: type ${JSON.stringify(f.type)} is outside the §23 enum`);
  if (!['High', 'Medium', 'Low'].includes(f.confidence)) problems.push(`${f.id}: confidence ${JSON.stringify(f.confidence)}`);
  if (!f.limitation) problems.push(`${f.id}: no limitation`);
  if (!(f.sources || []).some((s) => (s.url || '').startsWith('http'))) problems.push(`${f.id}: no source URL`);
}
if (problems.length) {
  console.error('FAIL: the evidence bank is not shippable:');
  for (const p of problems) console.error('  - ' + p);
  console.error('Fix research/eeat-findings.json and re-run `python ~/.claude/scripts/eeat_check.py --project .`');
  process.exit(1);
}

// `claim` and `why` are DELIBERATELY NOT EMITTED. The component must not be able to render
// the research verbatim: "written, not pasted" is a contract letter (q) enforces, and the
// simplest way to keep it is to make the paste impossible from inside the component.
const rows = findings.map((f) => ({
  id: f.id,
  heading: f.heading ?? null,
  type: f.type,
  confidence: f.confidence,
  first_hand: !!f.first_hand,
  limitation: f.limitation,
  observation_context: f.observation_context ?? null,
  assigned_slug: f.assigned_slug ?? null,
  sources: (f.sources || []).map((s) => ({ name: s.name, date: s.date ?? null, url: s.url })),
}));

const banner = `// GENERATED by scripts/gen-eeat.mjs from ${SRC} — do not edit by hand.\n` +
  `// ${rows.length} finding(s), researched ${raw.researched ?? 'unknown'}, niche ${JSON.stringify(raw.niche ?? '')}.\n` +
  `// contracts.md §23. Regenerate with \`npm run gen:eeat\`.\n`;

const ts = `${banner}
export interface EeatSource { name: string; date: string | null; url: string }
export interface EeatFindingRecord {
  id: string;
  heading: string | null;
  type: string;
  confidence: 'High' | 'Medium' | 'Low';
  first_hand: boolean;
  limitation: string;
  observation_context: string | null;
  assigned_slug: string | null;
  sources: EeatSource[];
}

export const EEAT_FINDINGS: EeatFindingRecord[] = ${JSON.stringify(rows, null, 2)} as const satisfies readonly EeatFindingRecord[] as EeatFindingRecord[];

export const EEAT_BY_SLUG: Record<string, EeatFindingRecord[]> = EEAT_FINDINGS.reduce(
  (acc, f) => {
    const s = f.assigned_slug;
    if (!s || s.startsWith('retired:')) return acc;
    (acc[s] ||= []).push(f);
    return acc;
  },
  {} as Record<string, EeatFindingRecord[]>,
);
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, ts, 'utf8');
const assigned = rows.filter((r) => r.assigned_slug && !r.assigned_slug.startsWith('retired:')).length;
console.log(`gen-eeat: wrote ${OUT} — ${rows.length} finding(s), ${assigned} assigned, ` +
  `${rows.filter((r) => r.first_hand).length} first-hand.`);
