#!/usr/bin/env python
"""seed_sme_quotes.py - write config/sme/quotes/<category>.json from the curated table below.

Every row was lifted from a transcript in sme/raw/ and re-read against that file before it was
entered here. Editing a quote string is NOT allowed: drop the row and pick another line.
Re-run after any edit, then `python scripts/build_sme_quotes.py --check`.
"""
import json
import os
import sys
from collections import defaultdict

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# speaker | credential | publisher | url | verified_against
EXPERTS = {
    "ferox": ("Dr Ferox", "General-practice veterinarian",
              "Dr Ferox (YouTube)", "https://www.youtube.com/watch?v=HikGz0KygXw", "caption-track"),
    "amylee": ("Amy Lee", "Certified professional pet groomer since 2003",
               "Go Groomer (YouTube)", "https://www.youtube.com/watch?v=Pt4yG4GcN9U", "caption-track"),
    "cellini": ("Dr Cellini", "Veterinary neurologist",
                "DVMCellini (YouTube)", "https://www.youtube.com/watch?v=GksJbVKQlvY", "caption-track"),
    "vanessa": ("Vanessa", "Professional dog groomer and pet educator",
                "Girl With Her Dogs (YouTube)", "https://www.youtube.com/watch?v=W99JFlvNZ9g", "caption-track"),
    "jones": ("Dr Andrew Jones", "Veterinarian",
              "Veterinary Secrets (YouTube)", "https://www.youtube.com/watch?v=DpphBJAMSh0", "caption-track"),
    "mccannwk": ("McCann Dog Training", "Professional trainers, roughly 500 dogs a week",
                 "McCann Dog Training (YouTube)", "https://www.youtube.com/watch?v=qNtwkSVr2Pw", "caption-track"),
    "mccann": ("Kayl McCann", "Professional dog trainer, 25 years",
               "McCann Dog Training (YouTube)", "https://www.youtube.com/watch?v=cuDfystslho", "transcript-file"),
    "chow": ("Dr Chow", "Singapore veterinarian",
             "Mediacorp, All Facts No Filter EP11", "https://www.youtube.com/watch?v=_tUC71YR4lU", "transcript-file"),
    "desmond": ("Desmond", "Former pet groomer, Singapore",
                "Mediacorp, All Facts No Filter EP11", "https://www.youtube.com/watch?v=_tUC71YR4lU", "transcript-file"),
    "spca": ("SPCA Singapore", "Animal welfare organisation",
             "CNA Insider, Talking Point", "https://www.youtube.com/watch?v=M8JgfWu290g", "transcript-file"),
    "joanne": ("Joanne Cheong", "Independent cat rescuer, Singapore",
               "CNA Insider, Talking Point", "https://www.youtube.com/watch?v=M8JgfWu290g", "transcript-file"),
    "terry": ("Terry", "Operator, Animal Lodge boarding facility, Singapore",
              "CNA Insider, Talking Point", "https://www.youtube.com/watch?v=M8JgfWu290g", "transcript-file"),
}

# expert, timestamp, value_test, category, quote, why, caution
ROWS = [
    # ---------------- poodle crosses -------------------------------------------------
    ("ferox", "00:00:12", "corrected-misconception", "breed-poodle-mix",
     "Mixing two breeds does not guarantee hybrid vigour, especially if the two breeds are prone to the same illness.",
     "Kills the single most common myth a poodle-cross buyer arrives with.",
     "Clinical impression from an Australian general practice, not a prevalence study."),
    ("ferox", "00:14:40", "mechanism", "breed-poodle-mix",
     "If you are crossing a poodle to a cocker spaniel, the resulting puppies are not going to be more resistant than either parent.",
     "Shows the no-hybrid-vigour rule applied to one specific cross.",
     "Australian caseload; no Singapore data."),
    ("ferox", "00:01:04", "mechanism", "breed-poodle-mix",
     "It's more a matter of deciding what problems you are willing and able to manage.",
     "Reframes breed choice from finding a healthy breed to matching a manageable problem list.",
     "none"),
    ("amylee", "00:12:46", "corrected-misconception", "breed-poodle-mix",
     "Curly coats are attractive and considered low shedding, but are not necessarily easy to care for.",
     "Separates low-shedding from low-maintenance before the buyer commits.",
     "North American grooming practice; frequency advice not adapted to Singapore humidity."),
    ("amylee", "00:09:55", "mechanism", "breed-poodle-mix",
     "The coat does not shed, but if it's not brushed out, the dead hairs can remain in the coat and become tangled with new hairs growing in. This will cause matting.",
     "Explains exactly why a non-shedding coat mats, which is the mechanism most owners never hear.",
     "none"),
    ("amylee", "00:26:05", "corrected-misconception", "breed-poodle-mix",
     "You will see that some golden doodles, especially the first generation, will see a double coat, and it sheds a lot.",
     "Honest disclosure that a first-generation doodle can shed heavily.",
     "Her observation from the grooming table, not a breeding study."),
    ("amylee", "00:13:29", "mechanism", "breed-poodle-mix",
     "The curly coat is a very high maintenance coat.",
     "One-line expectation setter for every poodle cross.",
     "none"),
    # ---------------- toy and small breeds --------------------------------------------
    ("ferox", "00:05:54", "mechanism", "breed-toy-small",
     "The smaller the dog, the more common it is.",
     "Ties luxating-patella risk directly to size, which is the buyer's actual choice variable.",
     "Said of poodles specifically; the size pattern is general but the phrasing is breed-scoped."),
    ("ferox", "00:01:40", "corrected-misconception", "breed-toy-small",
     "Teacups are just something you do not want to go near.",
     "A vet saying plainly that teacup lines are a health decision, not a size preference.",
     "none"),
    ("ferox", "00:16:04", "mechanism", "breed-toy-small",
     "Toy poodles are already small enough. You do not need to breed them even smaller.",
     "Names the breeding practice behind teacup health problems.",
     "none"),
    ("ferox", "00:02:55", "runnable-test", "breed-toy-small",
     "You can often see it when the puppies are sort of 8 to 10 weeks old, so before you choose one to bring home.",
     "Gives the buyer something to actually inspect in the puppy's mouth at viewing age.",
     "Refers to base-narrow canines; needs the surrounding explanation on the page."),
    ("jones", "00:00:18", "mechanism", "breed-toy-small",
     "It's a very common condition that happens with small breed dogs.",
     "Sets the expectation that a kneecap grade is normal to ask about in a small breed.",
     "Vendor conflict: this vet sells a joint supplement. Capped at two site-wide uses, no figures."),
    ("jones", "00:02:44", "corrected-misconception", "breed-toy-small",
     "Most of these guys can live completely fine without having any type of intervention, surgery, or anything major at all.",
     "Stops a mild patella grade from reading as a catastrophe.",
     "Vendor conflict as above. Must sit beside a see-your-vet line."),
    ("amylee", "00:11:10", "mechanism", "breed-toy-small",
     "A long coat is more likely to tangle and matt than many other coat types, especially in places where the coat moves.",
     "Tells a long-coat owner where to check before the mat forms.",
     "none"),
    ("amylee", "00:11:44", "runnable-test", "breed-toy-small",
     "If you find a tangle or a mat, do not ignore it. It will never go away on its own.",
     "A rule the owner can act on the day they feel one.",
     "none"),
    ("amylee", "00:12:06", "runnable-test", "breed-toy-small",
     "Never cut a mat out with scissors. The skin can get pulled into the mat if the mat is too tight and you will cut your dog.",
     "Prevents the most common at-home grooming injury.",
     "none"),
    ("mccann", "00:08:28", "corrected-misconception", "breed-toy-small",
     "It's not necessarily about the breed per se. It's often about the match between the breed and the person.",
     "Moves the buyer from breed shopping to fit.",
     "none"),
    ("mccann", "00:09:12", "corrected-misconception", "breed-toy-small",
     "We never want to use breed and personality traits as an excuse for why a dog can or cannot do something.",
     "Blocks breed fatalism in either direction.",
     "none"),
    ("ferox", "00:12:12", "runnable-test", "breed-toy-small",
     "The cough from a collapsing trachea sounds quite a lot like the cough from heart failure, so don't assume it's one or the other without getting it checked out.",
     "Stops an owner self-diagnosing the most common cough in a small senior dog.",
     "Australian general practice; clinical mechanism, not a Singapore prevalence claim."),
    ("ferox", "00:11:58", "mechanism", "breed-toy-small",
     "The symptoms also get worse with excessive weight, as it is very easy to overfeed an adorable little lap dog.",
     "Names the one variable the owner fully controls in a small-breed airway problem.",
     "Said of collapsing trachea in poodles."),
    ("ferox", "00:12:24", "mechanism", "breed-toy-small",
     "Often there will have been a physical incident such as jumping off a couch.",
     "Turns disc disease from bad luck into a household risk an owner can manage.",
     "Said of the smaller poodles."),
    ("ferox", "00:01:40", "mechanism", "breed-toy-small",
     "Poodles very commonly have hairy ears, and that hair can trap moisture, predisposing to ear infections.",
     "Explains the mechanism behind the most common small-breed vet visit.",
     "Poodle-specific, though the mechanism applies to other hairy-eared breeds."),
    ("ferox", "00:02:21", "mechanism", "breed-toy-small",
     "Tooth problems are also extremely common, with most of them requiring at least a dental scale during their lifetime.",
     "Puts a recurring lifetime cost in front of the buyer before purchase.",
     "Poodle-specific clinical impression, not a measured rate."),
    ("amylee", "00:08:28", "runnable-test", "breed-toy-small",
     "Regular brushing with a soft bristle brush, such as a bore bristle brush, can help get the loose dead hair out of the coat.",
     "Names the actual tool for a short-coated small breed.",
     "Said of smooth coats."),
    # ---------------- larger and working breeds ---------------------------------------
    ("mccann", "00:17:42", "mechanism", "breed-large-active",
     "They can run circles mentally and physically around people who don't really know what they're doing.",
     "Honest warning on the smart working breeds before purchase.",
     "Said of Border Collies."),
    ("mccann", "00:18:35", "corrected-misconception", "breed-large-active",
     "My border collies are by far the easiest to live with in my home.",
     "Balances the warning: the same breed is easy in the right hands.",
     "A professional trainer's household is not a typical one."),
    ("mccann", "00:14:45", "mechanism", "breed-large-active",
     "Is it harder than doing it with a Labrador or a Golden or a Border Collie? Yes. Yes it is. They just don't have that same willingness to please.",
     "Names the willingness-to-please axis that decides first-timer difficulty.",
     "Said of Huskies."),
    ("mccann", "00:21:57", "corrected-misconception", "breed-large-active",
     "A lot of them that I have seen have not been very friendly. They can be, to be transparent, on the nasty side.",
     "Disclosure a shop has every incentive to omit, which is why it builds trust.",
     "Said of Shiba Inu; one trainer's caseload, not a temperament survey."),
    ("mccann", "00:04:00", "mechanism", "breed-large-active",
     "Sometimes the dog is like five steps ahead of the owner and that can be problematic.",
     "Concrete picture of what an under-stimulated clever breed does to a household.",
     "Said of German Shepherds."),
    ("amylee", "00:14:47", "mechanism", "breed-large-active",
     "All double coated dogs need regular brushing that goes through the undercoat to the skin.",
     "The technique that decides whether a double coat mats in a humid climate.",
     "none"),
    ("cellini", "00:13:20", "mechanism", "cost-and-pricing",
     "Try to avoid pets with extreme features. The more extreme, the higher the average cost to maintain.",
     "Links a visible feature to a lifetime cost the buyer can predict.",
     "US market; he does not recommend buying designer breeds. Never frame as an endorsement."),
    ("amylee", "00:15:02", "corrected-misconception", "breed-large-active",
     "Although owners of double coated dogs swear that all this undercoat sheds because it can be seen all over the house, much of it doesn't.",
     "Corrects the belief that a shedding dog is self-clearing, which is what leads to matting.",
     "North American climate; the brushing principle transfers, frequency should be judged locally."),
    ("mccannwk", "00:00:00", "number", "breed-large-active",
     "Did you know that by the age of seven weeks, your puppy's brain is fully developed?",
     "Explains why a large working breed is ready to learn the day it comes home.",
     "Their framing of developmental readiness, not a cited neurological study."),
    # ---------------- cost and pricing ------------------------------------------------
    ("cellini", "00:04:58", "mechanism", "cost-and-pricing",
     "The most important thing to realize here is that recurring costs are going to scale with two things: number one is the size of your pet, and number two, the extent to which they have extreme features.",
     "Gives a buyer a two-variable model for predicting their own running costs.",
     "US market figures elsewhere in the source; this line carries no currency."),
    ("cellini", "00:02:51", "corrected-misconception", "cost-and-pricing",
     "You'd like to think you get what you pay for, but that just isn't always the case.",
     "Warns that a premium price can be demand, not quality.",
     "US market. He does not recommend buying designer breeds."),
    ("cellini", "00:03:12", "runnable-test", "cost-and-pricing",
     "If a breeder tells you the reason their puppy cost that much is because of how much health care they need ahead of time, that should send off alarm bells in your head.",
     "A test the buyer can apply to a price justification on the spot.",
     "US market."),
    ("cellini", "00:12:22", "mechanism", "cost-and-pricing",
     "Remember, smaller dogs cost less on average.",
     "Directly relevant where most of the catalogue is small breeds.",
     "US market averages."),
    ("cellini", "00:11:22", "mechanism", "cost-and-pricing",
     "Bear in mind almost every pet insurance company requires you to pay the vet first and then they reimburse you, so you'll still need the cash on hand.",
     "Corrects the assumption that insurance removes the need for savings.",
     "US insurers; confirm the reimbursement model of any Singapore policy."),
    ("cellini", "00:12:36", "runnable-test", "cost-and-pricing",
     "Your vet will always provide you with a cost estimate ahead of time, and if they don't, always ask.",
     "One sentence the owner can use at the counter.",
     "US practice norms."),
    ("cellini", "00:14:12", "mechanism", "cost-and-pricing",
     "Invest in preventative care. Regular checkups and preventative medication can save you money in the long run by avoiding costly treatments.",
     "The cheapest lever, stated by a specialist who sees the expensive end.",
     "US market."),
    ("chow", "00:09:20", "runnable-test", "cost-and-pricing",
     "Even if we do this and this, is there any actionable information, like, will it change things?",
     "The exact question to ask a vet before agreeing to a test. Singapore source.",
     "none"),
    ("chow", "00:09:26", "corrected-misconception", "cost-and-pricing",
     "We can do it for your peace of mind, but it's not going to do anything for the patient.",
     "A Singapore vet naming the difference between reassurance and treatment.",
     "none"),
    # ---------------- health and vet care ----------------------------------------------
    ("ferox", "00:00:54", "corrected-misconception", "health-and-vet",
     "All breeds will have health problems. Some are healthier than others, but none are perfect.",
     "Sets an honest baseline before any breed health section.",
     "none"),
    ("ferox", "00:17:38", "mechanism", "health-and-vet",
     "Many poodles manage to live and thrive into their late teens, although you will have to keep up with maintaining their coat.",
     "Pairs a good prognosis with the condition attached to it.",
     "Poodle-specific."),
    ("ferox", "00:16:34", "mechanism", "health-and-vet",
     "They will pick up on their owner's behaviour. If their owner is anxious, they will emulate that.",
     "Explains a behaviour problem owners usually blame on the dog.",
     "Said of poodles."),
    ("jones", "00:03:45", "runnable-test", "health-and-vet",
     "Something you should consider, and you probably haven't heard from your veterinarian, is physiotherapy.",
     "Names an option most owners are never offered.",
     "Vendor conflict: this vet sells supplements. Capped; must sit beside a see-your-vet line."),
    ("chow", "00:06:50", "mechanism", "health-and-vet",
     "The pet owner just felt like I was trying to sell them the test.",
     "A Singapore vet naming the trust problem from the other side of the counter.",
     "none"),
    ("desmond", "00:10:05", "corrected-misconception", "health-and-vet",
     "This shampoo, you have to mix it 20 pots of water.",
     "A first-hand account of dilution in a grooming salon, from someone who worked there.",
     "One former employee's account of one salon."),
    ("desmond", "00:14:49", "runnable-test", "health-and-vet",
     "You won't need to force them through any procedures.",
     "The standard to hold a groomer to.",
     "Said in a cat-grooming context."),
    # ---------------- first-time owners -------------------------------------------------
    ("mccannwk", "00:00:00", "mechanism", "first-time-owners",
     "We know that what puppies learn first, they learn best.",
     "Explains why week one matters more than month six.",
     "none"),
    ("mccannwk", "00:13:11", "corrected-misconception", "first-time-owners",
     "This week we have not done any walking training. We have not gone on even one walk together.",
     "Contradicts the new owner's instinct to start walks immediately.",
     "North American setting; adapt the toileting location for HDB."),
    ("mccannwk", "00:03:13", "runnable-test", "first-time-owners",
     "I know he usually has to pee after we've had a play. Because I'm learning about his schedule, it allows me to be more proactive and prevent those accidents.",
     "Turns toilet training from a clock into an observable pattern.",
     "none"),
    ("mccannwk", "00:13:14", "corrected-misconception", "first-time-owners",
     "Far too many puppy owners underestimate the value of handling exercises.",
     "Points at the skill that makes grooming and vet visits possible later.",
     "none"),
    ("cna-editorial", "", "", "", "", "", ""),  # placeholder removed below
    # ---------------- puppy care and training -------------------------------------------
    ("mccannwk", "00:05:20", "mechanism", "puppy-care-training",
     "One of the reasons why he is fairly comfortable in his crate already is because we introduced the crate the very first day he came home.",
     "Day-one action with a named consequence.",
     "none"),
    ("mccannwk", "00:05:48", "runnable-test", "puppy-care-training",
     "Take advantage of that crate position those first couple of nights home.",
     "Concrete first-night instruction.",
     "Assumes a crate beside the bed."),
    ("mccannwk", "00:07:18", "mechanism", "puppy-care-training",
     "If it's not followed with some sort of reward at this point in your puppy's training, it's going to start to lose value.",
     "Explains why calling the puppy's name constantly backfires.",
     "none"),
    ("mccannwk", "00:08:00", "mechanism", "puppy-care-training",
     "It is important that your puppy realizes that they should go in their crate and that it could be in a location where people are walking by all day long.",
     "The variation that prevents separation problems later.",
     "none"),
    # ---------------- buying safely ------------------------------------------------------
    ("vanessa", "00:14:23", "runnable-test", "buying-safely",
     "If the breeder doesn't ask you any questions about you and the life that you're going to provide for one of their animals, they simply don't care. Red flag.",
     "The single most diagnostic test a buyer can run, and it costs nothing.",
     "She is critical of pet-shop sales and of poodle crosses. Cite only on buyer-checklist pages."),
    ("vanessa", "00:11:57", "runnable-test", "buying-safely",
     "You should be able to meet at least one parent. The breeder should interview you because they care about where their animal is going.",
     "Two checks a buyer can insist on before paying.",
     "As above."),
    ("vanessa", "00:11:23", "runnable-test", "buying-safely",
     "Reputable breeders provide contracts with health guarantees and return clauses.",
     "Names the paperwork a buyer should ask to see.",
     "As above."),
    ("vanessa", "00:14:58", "corrected-misconception", "buying-safely",
     "The prices either seem too low, or they seem astronomically high.",
     "Warns that a bargain and a premium are both warning signs.",
     "As above."),
    ("vanessa", "00:19:27", "runnable-test", "buying-safely",
     "Do your research, ask questions, and don't be afraid to walk away from a situation that doesn't feel right.",
     "Gives the reader permission to leave, which is the action most fail to take.",
     "As above."),
    ("spca", "n/a", "corrected-misconception", "buying-safely",
     "When you buy pets, the education at point of sale is so important.",
     "Sets the standard a licensed shop should be measured against.",
     "SPCA is critical of the pet-retail sector generally."),
    ("joanne", "n/a", "number", "buying-safely",
     "I suspect that about 30 to 40 per cent of the cats that I have rescued before were actually from backyard breeders.",
     "A Singapore rescuer's own estimate of backyard-breeder supply.",
     "Her stated suspicion about cats, not a measured figure and not about dogs."),
    ("terry", "n/a", "mechanism", "buying-safely",
     "For our cats and dogs, we take care of them for life, so we do not euthanise them.",
     "A Singapore operator stating a lifetime-care policy, which is the standard a buyer should ask any seller about.",
     "One boarding operator's own policy, not an industry norm."),
    # ---------------- blog and guides ------------------------------------------------------
    ("amylee", "00:03:41", "mechanism", "blog-guides",
     "The six coat types are hairless, smooth, wire coated, wirehaired, long coated, curly coated, and double coated.",
     "Gives readers a framework instead of a breed list.",
     "none"),
    ("amylee", "00:30:50", "runnable-test", "blog-guides",
     "If they have good success brushing their dog at home, then I'm not going to leave four inches of coat on that dog, because they'll never be able to get it brushed out.",
     "Shows how clip length should be chosen from the owner's real habits.",
     "none"),
    ("mccann", "00:15:04", "mechanism", "blog-guides",
     "My toy poodle can escape things as well because she's very smart.",
     "Small does not mean simple, from a trainer who owns one.",
     "none"),
    ("mccann", "00:23:00", "mechanism", "blog-guides",
     "They always get paired with people who are very meek and soft and slow moving and passive, and these are big, powerful, busy dogs that need a lot of clear direction.",
     "Describes the mismatch mechanism that produces most rehoming.",
     "Said of Boxers, a breed not in this catalogue; use as a general mismatch example."),
    ("chow", "00:16:47", "mechanism", "blog-guides",
     "We remember our failures more than our successes.",
     "A Singapore vet on why practitioners are cautious.",
     "none"),
    ("spca", "n/a", "mechanism", "blog-guides",
     "Any day an animal has to spend in a shelter [...] is still a day away from a forever home.",
     "Frames the cost of a wrong match in the animal's terms.",
     "Marked elision: the original line contains a pause and further words."),
]


def main():
    out = defaultdict(list)
    counters = defaultdict(int)
    for row in ROWS:
        if not row[3]:
            continue  # placeholder row
        ekey, ts, vt, cat, quote, why, caution = row
        speaker, credential, publisher, url, verified = EXPERTS[ekey]
        counters[ekey] += 1
        assert "—" not in quote, "em dash in quote from " + ekey
        out[cat].append({
            "id": "%s-%d" % (ekey, counters[ekey]),
            "quote": quote,
            "speaker": speaker,
            "credential": credential,
            "publisher": publisher,
            "source_url": url,
            "timestamp": ts,
            "kind": "expert",
            "consent": "cited - attribution only",
            "verify": False,
            "verified_against": verified,
            "value_test": vt,
            "why": why,
            "caution": caution,
            "category": cat,
            "pages": [],
            "used_on": None,
        })
    d = os.path.join("config", "sme", "quotes")
    os.makedirs(d, exist_ok=True)
    total = 0
    for cat, entries in sorted(out.items()):
        p = os.path.join(d, cat + ".json")
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            json.dump(entries, f, ensure_ascii=False, indent=2)
            f.write("\n")
        print("%-22s %2d quotes -> %s" % (cat, len(entries), p))
        total += len(entries)
    print("TOTAL %d quotes across %d categories" % (total, len(out)))


if __name__ == "__main__":
    main()
